version: 0.2

phases:
    build:
      commands:
        - mvn clean package
    post_build:
      commands:
        - echo Success
env:
  variables:
    USERNAME: ${USERNAME}
    ANOTHER_ENV_VARIABLE: ${PASSWORD}

artifacts:
    files:
      - target/api-gateway.jar
    discard-paths: yes

